{"cells":[{"attachments":{},"cell_type":"markdown","metadata":{},"source":["# this program reads angles from images and stores ENUMs in database"]},{"cell_type":"code","execution_count":1,"metadata":{},"outputs":[{"name":"stderr","output_type":"stream","text":["2023-02-01 23:00:41.252702: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA\n","To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.\n"]}],"source":["import os\n","from tqdm import tqdm\n","from sql_face.sqldb import SQLDataBase\n","\n","home = os.path.expanduser(\"~\")\n","\n","db_name= 'colab_main_dataset' #'colab_main_dataset'\n","input_dir = os.path.join(home, 'video_resources', 'image_datasets')\n","output_dir = os.path.join(home, 'video_resources', 'sql_database')\n","database_names=['forenface','lfw','xqlfw','scface',] # 'lfw', 'scface',  'enfsi', 'enfsi2015', , 'utkface','chokepoint','forenface'\n","detector_names=['mtcnn'] # 'dlib', 'mtcnn', 'mtcnn_serfiq'\n","embedding_model_names=[\"ArcFace\"] # , \"Dlib\", \"ArcFace\",\n","attributes_to_update=['yaw','pitch','roll']  # 'gender', 'age', 'emotion', 'race'\n","quality_model_names = ['ser_fiq', 'tface'] # 'confusion_score', 'ser_fiq',\n","save_in_drive = False # To work in google colab\n","\n"]},{"cell_type":"code","execution_count":2,"metadata":{},"outputs":[],"source":["database = SQLDataBase(db_name=db_name,\n","                        input_dir = input_dir,\n","                        output_dir_name = output_dir,\n","                        database_names = database_names,\n","                        detector_names = detector_names,\n","                        embedding_model_names = embedding_model_names,\n","                        quality_model_names = quality_model_names)"]},{"attachments":{},"cell_type":"markdown","metadata":{},"source":["# thresholds calculated previously (excel)"]},{"cell_type":"code","execution_count":3,"metadata":{},"outputs":[],"source":["th = {\n","'pitch': [-16.47307851, -7.950750253, 0.710368788, 6.941161856, 99999],\n","'yaw': [10.84743824,\n","20.52868443,\n","99999],\n","'roll': [ \n","6.373882696,\n","13.32788435,\n","99999]}"]},{"cell_type":"code","execution_count":4,"metadata":{},"outputs":[{"name":"stderr","output_type":"stream","text":["INFO: Created TensorFlow Lite XNNPACK delegate for CPU.\n"]},{"ename":"OperationalError","evalue":"(sqlite3.OperationalError) no such column: image.image_quality\n[SQL: SELECT image.image_id AS image_image_id, image.path AS image_path, image.identity AS image_identity, image.source AS image_source, image.gender AS image_gender, image.age AS image_age, image.age_number AS image_age_number, image.emotion AS image_emotion, image.race AS image_race, image.yaw AS image_yaw, image.pitch AS image_pitch, image.roll AS image_roll, image.headgear AS image_headgear, image.glasses AS image_glasses, image.beard AS image_beard, image.other_occlusions AS image_other_occlusions, image.low_quality AS image_low_quality, image.image_quality AS image_image_quality, image.type AS image_type \nFROM image \nWHERE image.roll IS NULL]\n(Background on this error at: https://sqlalche.me/e/14/e3q8)","output_type":"error","traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mOperationalError\u001b[0m                          Traceback (most recent call last)","File \u001b[0;32m~/anaconda3/envs/sql-face/lib/python3.8/site-packages/sqlalchemy/engine/base.py:1819\u001b[0m, in \u001b[0;36mConnection._execute_context\u001b[0;34m(self, dialect, constructor, statement, parameters, execution_options, *args, **kw)\u001b[0m\n\u001b[1;32m   1818\u001b[0m     \u001b[39mif\u001b[39;00m \u001b[39mnot\u001b[39;00m evt_handled:\n\u001b[0;32m-> 1819\u001b[0m         \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mdialect\u001b[39m.\u001b[39;49mdo_execute(\n\u001b[1;32m   1820\u001b[0m             cursor, statement, parameters, context\n\u001b[1;32m   1821\u001b[0m         )\n\u001b[1;32m   1823\u001b[0m \u001b[39mif\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_has_events \u001b[39mor\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mengine\u001b[39m.\u001b[39m_has_events:\n","File \u001b[0;32m~/anaconda3/envs/sql-face/lib/python3.8/site-packages/sqlalchemy/engine/default.py:732\u001b[0m, in \u001b[0;36mDefaultDialect.do_execute\u001b[0;34m(self, cursor, statement, parameters, context)\u001b[0m\n\u001b[1;32m    731\u001b[0m \u001b[39mdef\u001b[39;00m \u001b[39mdo_execute\u001b[39m(\u001b[39mself\u001b[39m, cursor, statement, parameters, context\u001b[39m=\u001b[39m\u001b[39mNone\u001b[39;00m):\n\u001b[0;32m--> 732\u001b[0m     cursor\u001b[39m.\u001b[39;49mexecute(statement, parameters)\n","\u001b[0;31mOperationalError\u001b[0m: no such column: image.image_quality","\nThe above exception was the direct cause of the following exception:\n","\u001b[0;31mOperationalError\u001b[0m                          Traceback (most recent call last)","Cell \u001b[0;32mIn [4], line 9\u001b[0m\n\u001b[1;32m      5\u001b[0m face_parser \u001b[39m=\u001b[39m FaceParser()\n\u001b[1;32m      7\u001b[0m \u001b[39mfor\u001b[39;00m db \u001b[39min\u001b[39;00m database\u001b[39m.\u001b[39mdatabases:\n\u001b[0;32m----> 9\u001b[0m     images \u001b[39m=\u001b[39m (session\u001b[39m.\u001b[39;49mquery(Image)\u001b[39m.\u001b[39;49mfilter(Image\u001b[39m.\u001b[39;49mroll \u001b[39m==\u001b[39;49m \u001b[39mNone\u001b[39;49;00m)\u001b[39m.\u001b[39;49mall())\n\u001b[1;32m     10\u001b[0m \u001b[39m#images = (session.query(Image).filter(Image.yaw == None).all())\u001b[39;00m\n\u001b[1;32m     12\u001b[0m     n1 \u001b[39m=\u001b[39m \u001b[39m100\u001b[39m\n","File \u001b[0;32m~/anaconda3/envs/sql-face/lib/python3.8/site-packages/sqlalchemy/orm/query.py:2768\u001b[0m, in \u001b[0;36mQuery.all\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m   2752\u001b[0m \u001b[39mdef\u001b[39;00m \u001b[39mall\u001b[39m(\u001b[39mself\u001b[39m):\n\u001b[1;32m   2753\u001b[0m     \u001b[39m\"\"\"Return the results represented by this :class:`_query.Query`\u001b[39;00m\n\u001b[1;32m   2754\u001b[0m \u001b[39m    as a list.\u001b[39;00m\n\u001b[1;32m   2755\u001b[0m \n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m   2766\u001b[0m \u001b[39m            :ref:`faq_query_deduplicating`\u001b[39;00m\n\u001b[1;32m   2767\u001b[0m \u001b[39m    \"\"\"\u001b[39;00m\n\u001b[0;32m-> 2768\u001b[0m     \u001b[39mreturn\u001b[39;00m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_iter()\u001b[39m.\u001b[39mall()\n","File \u001b[0;32m~/anaconda3/envs/sql-face/lib/python3.8/site-packages/sqlalchemy/orm/query.py:2903\u001b[0m, in \u001b[0;36mQuery._iter\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m   2900\u001b[0m params \u001b[39m=\u001b[39m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_params\n\u001b[1;32m   2902\u001b[0m statement \u001b[39m=\u001b[39m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_statement_20()\n\u001b[0;32m-> 2903\u001b[0m result \u001b[39m=\u001b[39m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49msession\u001b[39m.\u001b[39;49mexecute(\n\u001b[1;32m   2904\u001b[0m     statement,\n\u001b[1;32m   2905\u001b[0m     params,\n\u001b[1;32m   2906\u001b[0m     execution_options\u001b[39m=\u001b[39;49m{\u001b[39m\"\u001b[39;49m\u001b[39m_sa_orm_load_options\u001b[39;49m\u001b[39m\"\u001b[39;49m: \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mload_options},\n\u001b[1;32m   2907\u001b[0m )\n\u001b[1;32m   2909\u001b[0m \u001b[39m# legacy: automatically set scalars, unique\u001b[39;00m\n\u001b[1;32m   2910\u001b[0m \u001b[39mif\u001b[39;00m result\u001b[39m.\u001b[39m_attributes\u001b[39m.\u001b[39mget(\u001b[39m\"\u001b[39m\u001b[39mis_single_entity\u001b[39m\u001b[39m\"\u001b[39m, \u001b[39mFalse\u001b[39;00m):\n","File \u001b[0;32m~/anaconda3/envs/sql-face/lib/python3.8/site-packages/sqlalchemy/orm/session.py:1712\u001b[0m, in \u001b[0;36mSession.execute\u001b[0;34m(self, statement, params, execution_options, bind_arguments, _parent_execute_state, _add_event, **kw)\u001b[0m\n\u001b[1;32m   1710\u001b[0m \u001b[39melse\u001b[39;00m:\n\u001b[1;32m   1711\u001b[0m     conn \u001b[39m=\u001b[39m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_connection_for_bind(bind)\n\u001b[0;32m-> 1712\u001b[0m result \u001b[39m=\u001b[39m conn\u001b[39m.\u001b[39;49m_execute_20(statement, params \u001b[39mor\u001b[39;49;00m {}, execution_options)\n\u001b[1;32m   1714\u001b[0m \u001b[39mif\u001b[39;00m compile_state_cls:\n\u001b[1;32m   1715\u001b[0m     result \u001b[39m=\u001b[39m compile_state_cls\u001b[39m.\u001b[39morm_setup_cursor_result(\n\u001b[1;32m   1716\u001b[0m         \u001b[39mself\u001b[39m,\n\u001b[1;32m   1717\u001b[0m         statement,\n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m   1721\u001b[0m         result,\n\u001b[1;32m   1722\u001b[0m     )\n","File \u001b[0;32m~/anaconda3/envs/sql-face/lib/python3.8/site-packages/sqlalchemy/engine/base.py:1631\u001b[0m, in \u001b[0;36mConnection._execute_20\u001b[0;34m(self, statement, parameters, execution_options)\u001b[0m\n\u001b[1;32m   1627\u001b[0m     util\u001b[39m.\u001b[39mraise_(\n\u001b[1;32m   1628\u001b[0m         exc\u001b[39m.\u001b[39mObjectNotExecutableError(statement), replace_context\u001b[39m=\u001b[39merr\n\u001b[1;32m   1629\u001b[0m     )\n\u001b[1;32m   1630\u001b[0m \u001b[39melse\u001b[39;00m:\n\u001b[0;32m-> 1631\u001b[0m     \u001b[39mreturn\u001b[39;00m meth(\u001b[39mself\u001b[39;49m, args_10style, kwargs_10style, execution_options)\n","File \u001b[0;32m~/anaconda3/envs/sql-face/lib/python3.8/site-packages/sqlalchemy/sql/elements.py:332\u001b[0m, in \u001b[0;36mClauseElement._execute_on_connection\u001b[0;34m(self, connection, multiparams, params, execution_options, _force)\u001b[0m\n\u001b[1;32m    328\u001b[0m \u001b[39mdef\u001b[39;00m \u001b[39m_execute_on_connection\u001b[39m(\n\u001b[1;32m    329\u001b[0m     \u001b[39mself\u001b[39m, connection, multiparams, params, execution_options, _force\u001b[39m=\u001b[39m\u001b[39mFalse\u001b[39;00m\n\u001b[1;32m    330\u001b[0m ):\n\u001b[1;32m    331\u001b[0m     \u001b[39mif\u001b[39;00m _force \u001b[39mor\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39msupports_execution:\n\u001b[0;32m--> 332\u001b[0m         \u001b[39mreturn\u001b[39;00m connection\u001b[39m.\u001b[39;49m_execute_clauseelement(\n\u001b[1;32m    333\u001b[0m             \u001b[39mself\u001b[39;49m, multiparams, params, execution_options\n\u001b[1;32m    334\u001b[0m         )\n\u001b[1;32m    335\u001b[0m     \u001b[39melse\u001b[39;00m:\n\u001b[1;32m    336\u001b[0m         \u001b[39mraise\u001b[39;00m exc\u001b[39m.\u001b[39mObjectNotExecutableError(\u001b[39mself\u001b[39m)\n","File \u001b[0;32m~/anaconda3/envs/sql-face/lib/python3.8/site-packages/sqlalchemy/engine/base.py:1498\u001b[0m, in \u001b[0;36mConnection._execute_clauseelement\u001b[0;34m(self, elem, multiparams, params, execution_options)\u001b[0m\n\u001b[1;32m   1486\u001b[0m compiled_cache \u001b[39m=\u001b[39m execution_options\u001b[39m.\u001b[39mget(\n\u001b[1;32m   1487\u001b[0m     \u001b[39m\"\u001b[39m\u001b[39mcompiled_cache\u001b[39m\u001b[39m\"\u001b[39m, \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mengine\u001b[39m.\u001b[39m_compiled_cache\n\u001b[1;32m   1488\u001b[0m )\n\u001b[1;32m   1490\u001b[0m compiled_sql, extracted_params, cache_hit \u001b[39m=\u001b[39m elem\u001b[39m.\u001b[39m_compile_w_cache(\n\u001b[1;32m   1491\u001b[0m     dialect\u001b[39m=\u001b[39mdialect,\n\u001b[1;32m   1492\u001b[0m     compiled_cache\u001b[39m=\u001b[39mcompiled_cache,\n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m   1496\u001b[0m     linting\u001b[39m=\u001b[39m\u001b[39mself\u001b[39m\u001b[39m.\u001b[39mdialect\u001b[39m.\u001b[39mcompiler_linting \u001b[39m|\u001b[39m compiler\u001b[39m.\u001b[39mWARN_LINTING,\n\u001b[1;32m   1497\u001b[0m )\n\u001b[0;32m-> 1498\u001b[0m ret \u001b[39m=\u001b[39m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_execute_context(\n\u001b[1;32m   1499\u001b[0m     dialect,\n\u001b[1;32m   1500\u001b[0m     dialect\u001b[39m.\u001b[39;49mexecution_ctx_cls\u001b[39m.\u001b[39;49m_init_compiled,\n\u001b[1;32m   1501\u001b[0m     compiled_sql,\n\u001b[1;32m   1502\u001b[0m     distilled_params,\n\u001b[1;32m   1503\u001b[0m     execution_options,\n\u001b[1;32m   1504\u001b[0m     compiled_sql,\n\u001b[1;32m   1505\u001b[0m     distilled_params,\n\u001b[1;32m   1506\u001b[0m     elem,\n\u001b[1;32m   1507\u001b[0m     extracted_params,\n\u001b[1;32m   1508\u001b[0m     cache_hit\u001b[39m=\u001b[39;49mcache_hit,\n\u001b[1;32m   1509\u001b[0m )\n\u001b[1;32m   1510\u001b[0m \u001b[39mif\u001b[39;00m has_events:\n\u001b[1;32m   1511\u001b[0m     \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mdispatch\u001b[39m.\u001b[39mafter_execute(\n\u001b[1;32m   1512\u001b[0m         \u001b[39mself\u001b[39m,\n\u001b[1;32m   1513\u001b[0m         elem,\n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m   1517\u001b[0m         ret,\n\u001b[1;32m   1518\u001b[0m     )\n","File \u001b[0;32m~/anaconda3/envs/sql-face/lib/python3.8/site-packages/sqlalchemy/engine/base.py:1862\u001b[0m, in \u001b[0;36mConnection._execute_context\u001b[0;34m(self, dialect, constructor, statement, parameters, execution_options, *args, **kw)\u001b[0m\n\u001b[1;32m   1859\u001b[0m             branched\u001b[39m.\u001b[39mclose()\n\u001b[1;32m   1861\u001b[0m \u001b[39mexcept\u001b[39;00m \u001b[39mBaseException\u001b[39;00m \u001b[39mas\u001b[39;00m e:\n\u001b[0;32m-> 1862\u001b[0m     \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_handle_dbapi_exception(\n\u001b[1;32m   1863\u001b[0m         e, statement, parameters, cursor, context\n\u001b[1;32m   1864\u001b[0m     )\n\u001b[1;32m   1866\u001b[0m \u001b[39mreturn\u001b[39;00m result\n","File \u001b[0;32m~/anaconda3/envs/sql-face/lib/python3.8/site-packages/sqlalchemy/engine/base.py:2043\u001b[0m, in \u001b[0;36mConnection._handle_dbapi_exception\u001b[0;34m(self, e, statement, parameters, cursor, context)\u001b[0m\n\u001b[1;32m   2041\u001b[0m     util\u001b[39m.\u001b[39mraise_(newraise, with_traceback\u001b[39m=\u001b[39mexc_info[\u001b[39m2\u001b[39m], from_\u001b[39m=\u001b[39me)\n\u001b[1;32m   2042\u001b[0m \u001b[39melif\u001b[39;00m should_wrap:\n\u001b[0;32m-> 2043\u001b[0m     util\u001b[39m.\u001b[39;49mraise_(\n\u001b[1;32m   2044\u001b[0m         sqlalchemy_exception, with_traceback\u001b[39m=\u001b[39;49mexc_info[\u001b[39m2\u001b[39;49m], from_\u001b[39m=\u001b[39;49me\n\u001b[1;32m   2045\u001b[0m     )\n\u001b[1;32m   2046\u001b[0m \u001b[39melse\u001b[39;00m:\n\u001b[1;32m   2047\u001b[0m     util\u001b[39m.\u001b[39mraise_(exc_info[\u001b[39m1\u001b[39m], with_traceback\u001b[39m=\u001b[39mexc_info[\u001b[39m2\u001b[39m])\n","File \u001b[0;32m~/anaconda3/envs/sql-face/lib/python3.8/site-packages/sqlalchemy/util/compat.py:208\u001b[0m, in \u001b[0;36mraise_\u001b[0;34m(***failed resolving arguments***)\u001b[0m\n\u001b[1;32m    205\u001b[0m     exception\u001b[39m.\u001b[39m__cause__ \u001b[39m=\u001b[39m replace_context\n\u001b[1;32m    207\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[0;32m--> 208\u001b[0m     \u001b[39mraise\u001b[39;00m exception\n\u001b[1;32m    209\u001b[0m \u001b[39mfinally\u001b[39;00m:\n\u001b[1;32m    210\u001b[0m     \u001b[39m# credit to\u001b[39;00m\n\u001b[1;32m    211\u001b[0m     \u001b[39m# https://cosmicpercolator.com/2016/01/13/exception-leaks-in-python-2-and-3/\u001b[39;00m\n\u001b[1;32m    212\u001b[0m     \u001b[39m# as the __traceback__ object creates a cycle\u001b[39;00m\n\u001b[1;32m    213\u001b[0m     \u001b[39mdel\u001b[39;00m exception, replace_context, from_, with_traceback\n","File \u001b[0;32m~/anaconda3/envs/sql-face/lib/python3.8/site-packages/sqlalchemy/engine/base.py:1819\u001b[0m, in \u001b[0;36mConnection._execute_context\u001b[0;34m(self, dialect, constructor, statement, parameters, execution_options, *args, **kw)\u001b[0m\n\u001b[1;32m   1817\u001b[0m                 \u001b[39mbreak\u001b[39;00m\n\u001b[1;32m   1818\u001b[0m     \u001b[39mif\u001b[39;00m \u001b[39mnot\u001b[39;00m evt_handled:\n\u001b[0;32m-> 1819\u001b[0m         \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mdialect\u001b[39m.\u001b[39;49mdo_execute(\n\u001b[1;32m   1820\u001b[0m             cursor, statement, parameters, context\n\u001b[1;32m   1821\u001b[0m         )\n\u001b[1;32m   1823\u001b[0m \u001b[39mif\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_has_events \u001b[39mor\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mengine\u001b[39m.\u001b[39m_has_events:\n\u001b[1;32m   1824\u001b[0m     \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mdispatch\u001b[39m.\u001b[39mafter_cursor_execute(\n\u001b[1;32m   1825\u001b[0m         \u001b[39mself\u001b[39m,\n\u001b[1;32m   1826\u001b[0m         cursor,\n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m   1830\u001b[0m         context\u001b[39m.\u001b[39mexecutemany,\n\u001b[1;32m   1831\u001b[0m     )\n","File \u001b[0;32m~/anaconda3/envs/sql-face/lib/python3.8/site-packages/sqlalchemy/engine/default.py:732\u001b[0m, in \u001b[0;36mDefaultDialect.do_execute\u001b[0;34m(self, cursor, statement, parameters, context)\u001b[0m\n\u001b[1;32m    731\u001b[0m \u001b[39mdef\u001b[39;00m \u001b[39mdo_execute\u001b[39m(\u001b[39mself\u001b[39m, cursor, statement, parameters, context\u001b[39m=\u001b[39m\u001b[39mNone\u001b[39;00m):\n\u001b[0;32m--> 732\u001b[0m     cursor\u001b[39m.\u001b[39;49mexecute(statement, parameters)\n","\u001b[0;31mOperationalError\u001b[0m: (sqlite3.OperationalError) no such column: image.image_quality\n[SQL: SELECT image.image_id AS image_image_id, image.path AS image_path, image.identity AS image_identity, image.source AS image_source, image.gender AS image_gender, image.age AS image_age, image.age_number AS image_age_number, image.emotion AS image_emotion, image.race AS image_race, image.yaw AS image_yaw, image.pitch AS image_pitch, image.roll AS image_roll, image.headgear AS image_headgear, image.glasses AS image_glasses, image.beard AS image_beard, image.other_occlusions AS image_other_occlusions, image.low_quality AS image_low_quality, image.image_quality AS image_image_quality, image.type AS image_type \nFROM image \nWHERE image.roll IS NULL]\n(Background on this error at: https://sqlalche.me/e/14/e3q8)"]}],"source":["from face_parser import FaceParser\n","from sql_face.tables import Image, EnfsiImage, VideoFrame, EnfsiVideoFrame, Yaw, Pitch, Roll\n","\n","session = database.session\n","face_parser = FaceParser()\n","\n","for db in database.databases:\n","    \n","    images = (session.query(Image).filter(Image.roll == None).all())\n","#images = (session.query(Image).filter(Image.yaw == None).all())\n","\n","    n1 = 100\n","    n= n1\n","    for image in tqdm(images,desc = f'Procesando {db.source}'):\n","        img = image.get_image(input_dir)\n","        faces, landmarks, angles = face_parser.detect_faces_lms_ang(img)\n","        if angles:\n","            pitch = angles[0][0]\n","            yaw = abs(angles[0][1])\n","            roll = abs(angles[0][2])\n","\n","            if not image.roll:\n","                image.roll = next(X_enum for X_enum, umbral in zip(Roll, th['roll']) if roll < umbral)  \n","            if not image.yaw:          \n","                image.yaw = next(X_enum for X_enum, umbral in zip(Yaw, th['yaw']) if yaw < umbral)\n","            if not image.pitch:\n","                image.pitch = next(X_enum for X_enum, umbral in zip(Pitch, th['pitch']) if pitch < umbral)\n","            if n:\n","                n -=1\n","            else:\n","                session.commit()\n","                n = n1\n","                \n","                \n","        session.commit()\n","    session.commit()\n","\n","            "]}],"metadata":{"kernelspec":{"display_name":"sql-face","language":"python","name":"python3"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.8.15"},"orig_nbformat":4,"vscode":{"interpreter":{"hash":"edd2314f85f22963f985d48f57a085e9a58a34ab11a3cd413d34968a1f6f2e55"}}},"nbformat":4,"nbformat_minor":2}
